# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-in-another-repo:
    uses: masayuki-inoue/github-actions-test-2/.github/workflows/reuse.yml@main
    with:
      friend_name: Masayuki
    # secrets:
    #   envPAT: ${{ secrets.envPAT }}

  show-outputs:
    needs:
      - call-workflow-in-another-repo
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call-workflow-in-another-repo.outputs.greeting_message }}

