name: Release

on:
  workflow_dispatch:

jobs:
  start_repository_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/dispatches \
          -d '{"event_type":"echo_message","client_payload":{"message":"Hello world"}}'
          
